### ISSUE TITLE
Ownership of children in Composite

### ISSUE THREAD

**Issue by rehans** [Geraet/Kompositum#4]
I guess the Kompositum::Composite is responsable for deleting all the children, right?. But how to do that in a neat way? Imagine I have sth like this:

``` c++
Kompositum::Composite composite(1);
composite.addChild(new Kompositum::Leaf(2));
```

This leaks inside of Kompositum::Composite of course. So how to do this inside Kompositum::Composite?

**Comment by mengelbrecht** [comment]
There are several options. The components could either be stored as `std::unique_ptr<Component>` or `std::shared_ptr<Component>` inside the composite. Another approach would be to make this configurable via a policy of some sorts. However then the whole thing turns header-only because of template usage.

**Comment by rehans** [comment]
Oki, that means the code would look like this?:

```
using Children = std::vector<std::unique_ptr<Component>>;
...
void addChild(Component* child) { children.emplace_back(child); }
```

How do I "transfer" a plain pointer into a std::unique_ptr?

**Comment by mengelbrecht** [comment]
It is highly advised to create `std::unique_ptr<T>` by using the `std::make_unique` function:
`auto leaf = std::make_unique<Leaf> (...)`. However keep in mind that `std::make_unique` is only available with C++14. Until we use C++14 I provided a function in `util.h`. See #5.

**Comment by rehans** [comment]
Nice one :+1:
